/* eslint-disable react-refresh/only-export-components */
import {
  Home,
  Building2,
  Store,
  Globe,
  MapPin,
  FileText,
  Phone,
  Mail,
  User,
  UserPlus,
  Users,
  Map,
  Search,
  Wallet,
  DollarSign,
  Star,
  Eye,
  MousePointerClick,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Ban,
  Shield,
  Bell,
  Settings,
  LogOut,
  Lock,
  Unlock,
  Sparkles,
  Trophy,
  Camera,
  Send,
  Linkedin,
  Key,
  ClipboardList,
  BedDouble,
  Maximize,
  Lightbulb,
  Calendar,
  Heart,
  X,
  ChevronLeft,
  ChevronRight,
  Menu,
  Calculator,
  Trash2,
  Edit,
  Plus,
  Minus,
  Upload,
  Image as ImageIcon,
  Clock,
  Check,
  ChevronDown,
  ExternalLink,
  MessageCircle,
  MoreHorizontal,
  Filter,
  Grid,
  List,
  SortAsc,
  SortDesc,
  RefreshCw,
  Save,
  Download,
  Share2,
  Copy,
  RotateCcw,
  History,
  Zap,
  Award,
  Crown,
  BadgeCheck,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Bookmark,
  BellRing,
  Smartphone,
  Monitor,
  Moon,
  Sun,
  LayoutDashboard,
  Layers,
  FileSearch,
  Receipt,
  CreditCard,
  Banknote,
  Percent,
  TrendingUpDown,
  BarChart,
  LineChart,
  AreaChart,
  Activity,
  Target,
  Compass,
  Navigation,
  Locate,
  LocateFixed,
  MapPinned,
  HomeIcon,
  Building,
  Warehouse,
  Factory,
  School,
  Hospital,
  Church,
  Castle,
  Tent,
  Trees,
  Mountain,
  Waves,
  Umbrella,
  Car,
  Bus,
  Train,
  Plane,
  Truck,
  Bike,
  Fuel,
  ParkingCircle,
  ShoppingBag,
  ShoppingCart,
  Package,
  Gift,
  Coffee,
  Utensils,
  Wifi,
  Tv,
  AirVent,
  Flame,
  Droplets,
  Thermometer,
  Wind,
  Snowflake,
  Fan,
  Battery,
  Plug,
  Power,
  ZapIcon,
  SunDim,
  SunMedium,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  UmbrellaIcon,
  ThermometerSun,
  ThermometerSnowflake,
} from 'lucide-react';

// Property Type Icons
export const PropertyTypeIcons = {
  apartment: { icon: Building2, label: 'آپارتمان', color: 'text-blue-500', bgColor: 'bg-blue-500' },
  villa: { icon: Home, label: 'ویلا', color: 'text-green-500', bgColor: 'bg-green-500' },
  office: { icon: Building, label: 'دفتر', color: 'text-purple-500', bgColor: 'bg-purple-500' },
  shop: { icon: Store, label: 'مغازه', color: 'text-orange-500', bgColor: 'bg-orange-500' },
  land: { icon: Globe, label: 'زمین', color: 'text-amber-600', bgColor: 'bg-amber-600' },
};

// Status Icons
export const StatusIcons = {
  pending: { icon: Clock, color: 'text-yellow-600', bgColor: 'bg-yellow-100 dark:bg-yellow-900/30' },
  approved: { icon: CheckCircle, color: 'text-green-600', bgColor: 'bg-green-100 dark:bg-green-900/30' },
  rejected: { icon: XCircle, color: 'text-red-600', bgColor: 'bg-red-100 dark:bg-red-900/30' },
  active: { icon: Zap, color: 'text-blue-600', bgColor: 'bg-blue-100 dark:bg-blue-900/30' },
};

// Toast Icons
export const ToastIcons = {
  success: { icon: CheckCircle, color: 'text-green-500' },
  error: { icon: XCircle, color: 'text-red-500' },
  warning: { icon: AlertTriangle, color: 'text-yellow-500' },
  info: { icon: Info, color: 'text-blue-500' },
};

// Navigation Icons
export const NavIcons = {
  home: Home,
  dashboard: LayoutDashboard,
  admin: Shield,
  user: User,
  users: Users,
  settings: Settings,
  logout: LogOut,
  login: Lock,
  register: UserPlus,
  search: Search,
  filter: Filter,
  menu: Menu,
  close: X,
  back: ChevronRight,
  forward: ChevronLeft,
  down: ChevronDown,
  calculator: Calculator,
  heart: Heart,
  bell: Bell,
  bellRing: BellRing,
  bookmark: Bookmark,
  share: Share2,
  more: MoreHorizontal,
};

// Stats Icons
export const StatsIcons = {
  ads: { icon: Home, color: 'from-blue-500 to-blue-600', bgGradient: 'from-blue-500 to-blue-600' },
  views: { icon: Eye, color: 'from-green-500 to-emerald-600', bgGradient: 'from-green-500 to-emerald-600' },
  clicks: { icon: MousePointerClick, color: 'from-purple-500 to-purple-600', bgGradient: 'from-purple-500 to-purple-600' },
  users: { icon: Users, color: 'from-orange-500 to-orange-600', bgGradient: 'from-orange-500 to-orange-600' },
  pending: { icon: Clock, color: 'from-yellow-500 to-yellow-600', bgGradient: 'from-yellow-500 to-yellow-600' },
  approved: { icon: CheckCircle, color: 'from-green-500 to-emerald-600', bgGradient: 'from-green-500 to-emerald-600' },
  rejected: { icon: XCircle, color: 'from-red-500 to-red-600', bgGradient: 'from-red-500 to-red-600' },
  total: { icon: BarChart3, color: 'from-blue-500 to-purple-600', bgGradient: 'from-blue-500 to-purple-600' },
};

// Feature Icons
export const FeatureIcons = {
  location: MapPin,
  area: Maximize,
  rooms: BedDouble,
  price: Wallet,
  phone: Phone,
  email: Mail,
  seller: User,
  description: FileText,
  map: Map,
  images: ImageIcon,
  upload: Upload,
  calendar: Calendar,
  time: Clock,
  date: Calendar,
  notes: ClipboardList,
  adminNotes: Shield,
  status: BadgeCheck,
  rating: Star,
  premium: Crown,
  featured: Sparkles,
  verified: BadgeCheck,
  favorite: Heart,
  delete: Trash2,
  edit: Edit,
  add: Plus,
  remove: Minus,
  save: Save,
  refresh: RefreshCw,
  download: Download,
  share: Share2,
  copy: Copy,
  external: ExternalLink,
  message: MessageCircle,
  lightbulb: Lightbulb,
  trophy: Trophy,
  award: Award,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  flag: Flag,
  ban: Ban,
  alert: AlertTriangle,
  error: AlertCircle,
  info: Info,
  success: CheckCircle,
  warning: AlertTriangle,
};

// Social Icons
export const SocialIcons = {
  instagram: Camera,
  telegram: Send,
  whatsapp: MessageCircle,
  linkedin: Linkedin,
};

// Footer Feature Icons
export const FooterFeatureIcons = {
  buy: Home,
  sell: DollarSign,
  rent: Key,
  consult: BarChart3,
  credit: CheckCircle,
  estimate: TrendingUp,
};

// Testimonial Avatars (using initials instead of emojis for professionalism)
export const getTestimonialAvatar = (index) => {
  const colors = [
    'bg-blue-500',
    'bg-green-500',
    'bg-purple-500',
    'bg-orange-500',
    'bg-pink-500',
    'bg-teal-500',
  ];
  return colors[index % colors.length];
};

// Re-export all icons for direct use
export {
  Home,
  Building2,
  Store,
  Globe,
  MapPin,
  FileText,
  Phone,
  Mail,
  User,
  Users,
  UserPlus,
  Map,
  Search,
  Wallet,
  DollarSign,
  Star,
  Eye,
  MousePointerClick,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Ban,
  Shield,
  Bell,
  Settings,
  LogOut,
  Lock,
  Unlock,
  Sparkles,
  Trophy,
  Camera,
  Send,
  Linkedin,
  Key,
  ClipboardList,
  BedDouble,
  Maximize,
  Lightbulb,
  Calendar,
  Heart,
  X,
  ChevronLeft,
  ChevronRight,
  Menu,
  Calculator,
  Trash2,
  Edit,
  Plus,
  Minus,
  Upload,
  ImageIcon,
  Clock,
  Check,
  ChevronDown,
  ExternalLink,
  MessageCircle,
  MoreHorizontal,
  Filter,
  Grid,
  List,
  SortAsc,
  SortDesc,
  RefreshCw,
  Save,
  Download,
  Share2,
  Copy,
  RotateCcw,
  History,
  Zap,
  Award,
  Crown,
  BadgeCheck,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Bookmark,
  BellRing,
  Smartphone,
  Monitor,
  Moon,
  Sun,
  LayoutDashboard,
  Layers,
  FileSearch,
  Receipt,
  CreditCard,
  Banknote,
  Percent,
  TrendingUpDown,
  BarChart,
  LineChart,
  AreaChart,
  Activity,
  Target,
  Compass,
  Navigation,
  Locate,
  LocateFixed,
  MapPinned,
  HomeIcon,
  Building,
  Warehouse,
};

// Icon wrapper component for consistent sizing
export const IconWrapper = ({ icon, size = 20, className = '', ...props }) => {
  const Component = icon;
  return <Component size={size} className={className} {...props} />;
};

// Property type icon component
export const PropertyTypeIcon = ({ type, size = 20, className = '' }) => {
  const config = PropertyTypeIcons[type] || PropertyTypeIcons.apartment;
  const Icon = config.icon;
  return <Icon size={size} className={`${config.color} ${className}`} />;
};

// Status icon component
export const StatusIcon = ({ status, size = 20, className = '' }) => {
  const config = StatusIcons[status] || StatusIcons.pending;
  const Icon = config.icon;
  return <Icon size={size} className={`${config.color} ${className}`} />;
};
